name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build clang

    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=clang++

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build --output-on-failure
